"""empty message

Revision ID: 0b8df71e4900
Revises: 
Create Date: 2019-11-21 21:12:20.117802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8df71e4900'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_teacher', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_teacher', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_teacher', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_teacher', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
